python Main.py https:\github.com\apache\commons-math http:\issues.apache.org\jira\projects\MATH hey_brother "project = MATH AND issuetype = Bug AND createdDate >= '2000/05/21' ORDER BY  createdDate ASC"
python Main.py https:\github.com\apache\commons-compress http:\issues.apache.org\jira\projects\COMPRESS hey_brother "project = COMPRESS AND issuetype = Bug AND createdDate >= '2000/01/22' ORDER BY  createdDate ASC"
python Main.py https:\github.com\apache\commons-lang http:\issues.apache.org\jira\projects\LANG hey_brother "project = LANG AND issuetype = Bug AND createdDate >= '2000/01/22' ORDER BY  createdDate ASC"
python Main.py https:\github.com\apache\tika http:\issues.apache.org\jira\projects\TIKA hey_brother "project = TIKA AND issuetype = Bug AND createdDate >= '2012/11/26' ORDER BY  createdDate ASC"
python Main.py https:\github.com\apache\jackrabbit-oak http:\issues.apache.org\jira\projects\OAK hey_brother "project = OAK AND issuetype = Bug AND createdDate >= '2000/01/22' ORDER BY  createdDate ASC"
python Main.py https:\github.com\apache\maven http:\issues.apache.org\jira\projects\MNG hey_brother "project = MNG AND issuetype = Bug AND createdDate >= '2000/01/22' ORDER BY  createdDate ASC"
python Main.py https:\github.com\apache\flink http:\issues.apache.org\jira\projects\FLINK hey_brother "project = FLINK AND issuetype = Bug AND createdDate >= '2000/01/22' ORDER BY  createdDate ASC"
python Main.py https:\github.com\apache\commons-logging http:\issues.apache.org\jira\projects\LOGGING hey_brother "project = LOGGING AND issuetype = Bug AND createdDate >= '2000/01/22' ORDER BY  createdDate ASC"
python Main.py https:\github.com\apache\wicket http:\issues.apache.org\jira\projects\WICKET hey_brother  "project = WICKET AND issuetype = Bug AND createdDate >= '2000/01/22' ORDER BY  createdDate ASC"

