python Main.py https:\github.com\apache\tika http:\issues.apache.org\jira\projects\TIKA hey_brother "project = TIKA AND issuetype = Bug AND createdDate >= '2018/01/22' ORDER BY  createdDate ASC"
python Main.py https:\github.com\apache\jackrabbit-oak http:\issues.apache.org\jira\projects\OAK "project = OAK AND issuetype = Bug AND createdDate >= '2018/01/22' ORDER BY  createdDate ASC"
python Main.py https:\github.com\apache\wicket http:\issues.apache.org\jira\projects\WICKET "project = WICKET AND issuetype = Bug AND createdDate >= '2018/01/22' ORDER BY  createdDate ASC"
python Main.py https:\github.com\apache\maven http:\issues.apache.org\jira\projects\MNG "project = MNG AND issuetype = Bug AND createdDate >= '2018/01/22' ORDER BY  createdDate ASC"
python Main.py https:\github.com\apache\flink http:\issues.apache.org\jira\projects\FLINK "project = FLINK AND issuetype = Bug AND createdDate >= '2018/01/22' ORDER BY  createdDate ASC"
python Main.py https:\github.com\apache\commons-logging http:\issues.apache.org\jira\projects\LOGGING "project = LOGGING AND issuetype = Bug AND createdDate >= '2018/01/22' ORDER BY  createdDate ASC"
python Main.py https:\github.com\apache\commons-math http:\issues.apache.org\jira\projects\MATH "project = MATH AND issuetype = Bug AND createdDate >= '2018/01/22' ORDER BY  createdDate ASC"
